# Generated by Django 3.0.6 on 2020-05-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapen', '0005_auto_20200508_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='airsoft',
            name='modeltype',
            field=models.CharField(choices=[('RIFLE', 'Rifle'), ('PISTOL', 'Pistol'), ('SHOTGUN', 'Shotgun'), ('SMG', 'Smg'), ('MACHINGEGUN', 'MachingeGun')], default=(('RIFLE', 'Rifle'), ('PISTOL', 'Pistol'), ('SHOTGUN', 'Shotgun'), ('SMG', 'Smg'), ('MACHINGEGUN', 'MachingeGun')), max_length=11),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='adptors',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='airnozzle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='anti_reversal_latches',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='bushing_bearings',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='charging_handles',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='conversion_kit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='cut_off_levers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='cylinder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='cylinder_heads',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='cylinder_tuneup',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='flash_hider',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='front_assembly',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='fuse',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='gas_block',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='gearbox',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='gears',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='hand_grip',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='hand_guard',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='hop_up',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='inner_barrels',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='magzine_catch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='mosfet',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='motor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='outer_barrels',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='pins',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='piston_heads',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='pistons',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='rail_accessories',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='rails',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='receivers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='selector_plate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='selector_switch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='shims',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='sight',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='sling_adapeters',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='spring',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='spring_guides',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='stock',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='tappert_plate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='text',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='trigger',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='trigger_guard',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='tune_upkit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='under_barrel',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='vertical_grips',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='wiring_mosfet',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
