# Generated by Django 3.0.6 on 2020-05-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapen', '0006_auto_20200508_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='airsoft',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='modeltype',
            field=models.CharField(choices=[('RIFLE', 'Rifle'), ('PISTOL', 'Pistol'), ('SHOTGUN', 'Shotgun'), ('SMG', 'Smg'), ('MACHINGEGUN', 'Machinge Gun')], default=(('RIFLE', 'Rifle'), ('PISTOL', 'Pistol'), ('SHOTGUN', 'Shotgun'), ('SMG', 'Smg'), ('MACHINGEGUN', 'Machinge Gun')), max_length=11),
        ),
        migrations.AlterField(
            model_name='airsoft',
            name='text',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
