# Generated by Django 3.0.6 on 2020-05-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapen', '0007_auto_20200510_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='airsoft',
            name='my_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
