# Generated by Django 3.0.6 on 2020-05-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapen', '0008_airsoft_my_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airsoft',
            name='my_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
